### ISSUE TITLE
Release 0.8.0 firmware (modules & BEES)

### ISSUE THREAD

**Issue by boqs** [tehn/aleph#303]
- [x] Add 'dummy' outputs to all zero-output BEES operators ( this may or may not be necessary for problem-free presetting with oplist deletion/insertion, but it's the safe option and doesn't impact usability)SCREEN, BIGNUM, `BARS, SERIAL, BARS8, MIDI_OUT_CC (included in PR #301)
- [X] ~~add 'dummy' param at start of all module descriptors - again, this is a safe option that won't affect usability.  Modules earmarked for inclusion in 0.8.0: waves, lines, fmsynth.~~ dummy param unnecessary after reverting ecf1b32 ( PR #301 up-to-date)
- [X] ~~fix broken dsyn, acid, add dummy param at start of these ops~~  ecf1b32 broke these, they're fixed in PR #301
- [x] appraisal of lines' mixer-section design changes by @catfact & amends if required (writehead fades reverted in PR#301)
- [X] ~~make lines write heads fade in/out on write_start & stress-test the change~~ reverted in PR #301, pushing back till it can be done properly
- [x] Get updated BEES docs from Yann_Coppier on the forum, dump these into the repo plain text (included in PR #301)
- [x] update midi ops in repo BEES docs (included in PR #301)
- [x] add CKDIV op to repo BEES docs (included in PR #301)
- [x] amend repo BEES docs for TIMER (included in PR #301)
- [x] add LINLIN to BEES docs (included in PR #301)
- [x] add LIST4 to BEES docs (included in PR #301)
- [X] add inputs for external pattern meta-sequencing to kria & whitewhale operators (included in PR #301)
- [x] increment module version numbers (PR #306)
- [x] tag version numbers in git (PR #306)
- [x] prepare sdcard image for release
- [ ] final rounds of testing after sleep - this should take the form of more focussed/interesting patches
